### ISSUE TITLE
Port 9091 not mapped to all interfaces

### ISSUE THREAD

**Issue by jplu** [couchbaselabs/elasticsearch-transport-couchbase#138]
Hi,

I'm currently using Elasticsearch 2.3.4 and Couchbase 4.1.0. In my Elasticsearch configuration I set multiple network interface that are properly handled and mapped by Elasticsearch as I can use it through all the interfaces. The problem is coming from the port 9091 that is mapped to only one interface randomly. An example on two machines where Elasticsearch is installed.

With machine 1:
```
netstat -nat | grep LISTEN
tcp        0      0 127.0.0.11:44631        0.0.0.0:*          LISTEN      
tcp        0      0 ::ffff:10.0.0.3:9091    :::*                    LISTEN      
tcp        0      0 ::ffff:10.0.0.3:9200    :::*                    LISTEN      
tcp        0      0 ::ffff:10.1.0.3:9200    :::*                    LISTEN      
tcp        0      0 ::ffff:10.0.0.3:9300    :::*                    LISTEN      
tcp        0      0 ::ffff:10.1.0.3:9300    :::*                    LISTEN
```

And machine 2:
```
tcp        0      0 127.0.0.11:34461        0.0.0.0:*          LISTEN      
tcp        0      0 ::ffff:10.1.0.2:9091    :::*                    LISTEN      
tcp        0      0 ::ffff:10.1.0.2:9200    :::*                    LISTEN      
tcp        0      0 ::ffff:10.0.0.2:9200    :::*                    LISTEN      
tcp        0      0 ::ffff:10.1.0.2:9300    :::*                    LISTEN      
tcp        0      0 ::ffff:10.0.0.2:9300    :::*                    LISTEN
```

Both machine belongs to two different networks, we can see that the ports 9200 and 9300 are correctly mapped and reachable through the two networks, but the port 9091 is mapped to only one of each, and not over the same network. My Elasticsearch configuration file looks like this:

```
cluster:
    name: ${CLUSTER_NAME}

    node:
        master: ${NODE_MASTER}
        data: ${NODE_DATA}

        path:
            data: /data/data
            logs: /data/log
            plugins: /elasticsearch/plugins
            work: /data/work

bootstrap.mlockall: true

network.host: _site_
http.enabled: ${HTTP_ENABLE}

discovery.zen.ping.multicast.enabled: ${MULTICAST}
discovery.zen.ping.multicast.ttl: 30
index.number_of_shards: 5
index.number_of_replicas: 1
index.refresh_interval: 5s
couchbase.password: password
couchbase.username: username
```

Did I do something wrong in my configuration file or is it a bug from the transport plugin?

Thanks in advance for any help.
